workspace: 
  src: 'AutoDeploy POC DEV'
  trg: 'AutoDeploy POC TEST'
connections:
  pbi_connection:
    src: autodeploy pbi-service-api admin
    trg: autodeploy pbi-service-api admin
  fabric_connection: 
    src: autodeploy fabric-service-api admin
    trg: autodeploy fabric-service-api admin

items:
  - Fabric_Deploy_Lakehouse.Lakehouse
  - 01_Transfer_Active_Items_Unit.Notebook
  - Load_Fabric_Deploy_E2E.DataPipeline

autodeploy_lakehouse_semantic_models: